name: Publish to PyPI

on: push
#  release:
#    types: [published]

jobs:
  publish:
    uses: jfigura/pytoo/.github/workflows/check.yaml@fix-publishing
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
      - run: echo "${HOME}/.poetry/bin" >> $GITHUB_PATH
      - run: poetry install
      - run: make check
      - run: poetry config pypi-token.pypi "${{ secrets.PYPI_API_KEY }}"
      - run: poetry publish --build
