name: Publish to PyPI

on: push
#  release:
#    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/check.yaml
      - run: poetry config pypi-token.pypi "${{ secrets.PYPI_API_KEY }}"
      - run: poetry publish --build
