name: Publish to PyPI

on: push
#  release:
#    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: jfigura/pytoo/.github/workflows/check.yaml@fix-publishing
      - run: poetry config pypi-token.pypi "${{ secrets.PYPI_API_KEY }}"
      - run: poetry publish --build
