name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/check
      - run: poetry config pypi-token.pypi "${{ secrets.PYPI_API_KEY }}"
      - run: poetry publish --build
